import = ["/home/zhews/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "NotoSansM Nerd Font"
style = "Regular"

[window]
opacity = 0.9
